# Generated by Django 5.2.12 on 2026-06-08 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sheet_department_label',
            field=models.CharField(blank=True, help_text='Displayed on attendance sheet e.g. SY- CE\\IT- 1', max_length=150),
        ),
        migrations.AddField(
            model_name='department',
            name='sheet_semester_label',
            field=models.CharField(blank=True, help_text='Displayed on attendance sheet e.g. III- ODD-2025', max_length=150),
        ),
        migrations.CreateModel(
            name='AttendanceSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('IPE', 'IPE Attendance Sheet'), ('GP', 'GP Attendance Sheet')], max_length=5)),
                ('template_file', models.FileField(upload_to='attendance_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_templates', to='portal.department')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_templates', to='portal.semester')),
            ],
        ),
    ]
