# Generated by Django 5.2.12 on 2026-06-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_department_sheet_department_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['field_scope', 'order']},
        ),
        migrations.AddField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Comma-separated options for dropdown fields'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='field_scope',
            field=models.CharField(choices=[('GROUP', 'Group Information'), ('MEMBER', 'Individual / Member Information')], default='GROUP', max_length=10),
        ),
        migrations.AddField(
            model_name='gpgroup',
            name='gender_diversity',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='gpgroup',
            name='group_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gpgroup',
            name='religion_diversity',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='gpgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('yes_no', 'Yes / No'), ('select', 'Dropdown Select')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='gpgroup',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Project Title'),
        ),
        migrations.CreateModel(
            name='ProjectCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_cases', to='portal.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cases', to='portal.semester')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gpgroup',
            name='project_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='portal.projectcase'),
        ),
        migrations.CreateModel(
            name='GPGroupMemberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('member_data', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_details', to='portal.gpgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_member_details', to='portal.student')),
            ],
            options={
                'ordering': ['student__roll_no'],
                'unique_together': {('group', 'student')},
            },
        ),
    ]
