# Generated by Django 5.2.12 on 2026-06-09 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_facultydutyassignment_markentry_mark_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='syllabus/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for semester-wide (all departments).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='portal.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='portal.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='portal.subject')),
            ],
            options={
                'verbose_name_plural': 'Subject syllabi',
                'ordering': ['subject__name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField(help_text='Paper phase e.g. 1, 2, 3')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='papers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for semester-wide (all departments).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='portal.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='portal.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='portal.subject')),
            ],
            options={
                'ordering': ['subject__name', 'phase'],
                'unique_together': {('subject', 'semester', 'department', 'phase')},
            },
        ),
    ]
