# Generated by Django 5.2.12 on 2026-06-09 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_subjectsyllabus_subjectpaper'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultydutyassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_external',
            field=models.BooleanField(default=False, help_text='External examiner — may share login if matched to existing faculty.'),
        ),
        migrations.AddField(
            model_name='facultydutyassignment',
            name='duty_role',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=10),
        ),
        migrations.AddField(
            model_name='facultydutyassignment',
            name='room_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facultydutyassignment',
            name='time_slot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='facultydutyassignment',
            unique_together={('faculty', 'department', 'subject', 'exam_type', 'batch', 'duty_date', 'duty_role')},
        ),
        migrations.CreateModel(
            name='DutyScheduleUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_file', models.FileField(upload_to='duty_schedules/')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_uploads', to='portal.department')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='facultydutyassignment',
            name='schedule_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='portal.dutyscheduleupload'),
        ),
    ]
