# Generated by Django 5.2.12 on 2026-06-15 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_external_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydutyassignment',
            name='marks_locked',
            field=models.BooleanField(default=False, help_text='When set, faculty and department admin cannot edit marks.'),
        ),
        migrations.AddField(
            model_name='facultydutyassignment',
            name='marks_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultydutyassignment',
            name='marks_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_marks_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultydutyassignment',
            name='marks_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
