# Generated by Django 5.2.12 on 2026-06-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_subject_type_gp_linked_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='gp_submission_deadline',
            field=models.DateTimeField(blank=True, help_text='After this date and time students cannot submit or edit GP projects.', null=True),
        ),
    ]
