# Generated by Django 5.2.12 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_department_gp_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpgroupmemberdetail',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Area name'),
        ),
        migrations.AddField(
            model_name='gpgroupmemberdetail',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
