# Generated by Django 5.2.12 on 2026-07-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_gpgroupmemberdetail_region_religion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPGroupFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_selection', models.CharField(max_length=200)),
                ('batches_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_formations', to='portal.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_formations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department__name', 'subject_selection'],
                'unique_together': {('department', 'subject_selection')},
            },
        ),
    ]
