# Generated by Django 5.2.12 on 2026-07-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_gpgroupformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPDutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_selection', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=20)),
                ('split_index', models.PositiveSmallIntegerField()),
                ('group_ids', models.JSONField(blank=True, default=list)),
                ('internal_faculty_other', models.CharField(blank=True, max_length=200)),
                ('external_faculty_name', models.CharField(blank=True, max_length=200)),
                ('duty_date', models.DateField()),
                ('room_no', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_duties_assigned', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_duty_assignments', to='portal.department')),
                ('internal_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_internal_duties', to='portal.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_duty_assignments', to='portal.subject')),
            ],
            options={
                'ordering': ['-duty_date', 'batch', 'split_index'],
            },
        ),
    ]
