# Generated by Django 5.2.12 on 2026-07-14 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_gp_duty_marks_and_external_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPEInvitationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_date', models.CharField(help_text='e.g. 17 Feb. 2025', max_length=100)),
                ('subject_line', models.CharField(default='Appointment as an External Examiner for conducting Internal Practical Examination of B.E. Semester-III', max_length=400)),
                ('subject_name', models.CharField(max_length=250)),
                ('practical_date', models.CharField(help_text='e.g. 20 February 2025', max_length=100)),
                ('branch', models.CharField(default='CE/IT/CSD/AIML/AIDS/RAI/CSE/CST/CSIT/CEA', max_length=200)),
                ('exam_time', models.CharField(default='9:00 am onwards', max_length=100)),
                ('excel_file', models.FileField(blank=True, upload_to='invitation_excels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipe_invitation_batches_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipe_invitation_batches', to='portal.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPEInvitationFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('college_name', models.CharField(blank=True, max_length=300)),
                ('city_state', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='portal.ipeinvitationbatch')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
