# Generated by Django 5.2.12 on 2026-07-14 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_ipe_invitation_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPEInvitationSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, upload_to='invitation_signatures/')),
                ('advisor_title', models.CharField(default='Advisor', max_length=100)),
                ('advisor_name', models.CharField(default='(Mr Rohit Patel)', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipe_invitation_signatures_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPE Invitation Signature',
                'verbose_name_plural': 'IPE Invitation Signatures',
            },
        ),
    ]
