# Generated by Django 5.2.12 on 2026-07-14 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_ipe_invitation_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipeinvitationbatch',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipe_invitation_batches', to='portal.subject'),
        ),
        migrations.AddField(
            model_name='ipeinvitationsignature',
            name='subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipe_invitation_signature', to='portal.subject'),
        ),
    ]
